### PR TITLE
Added utf-8 encoding, email, copyright symbol

### PR DESCRIPTION
**Pull request by cclauss**
- Added `key_title_dict()` to reduce boilerplate
- Used `str.format()` instead of templates.
- Added more **metadata** things, etc.

Really cool idea!!!

### CODE REVIEW

**Comment by lukaskollmer** [comment]
Just out of curiosity: Why did you choose the Apache License instead of a MIT license? Is that just your preferred choice or is that because it's a Python repo?

**Comment by cclauss** [comment]
Personal choice.  I find Apache does not constrain folks from making money from their work.  Some of the copyleft and GPL licenses do not fit my sense of freedom.  https://opensource.org/licenses  There is a new license called **Fair Source** that _might_ become of interest... https://fair.io/

**Comment by cclauss** [comment]
This is your repo so for sure, it is you that picks the license, not me.  You can change or remove this text as you see fit.  I merely put Apache because that is what I use.

**Comment by lukaskollmer** [comment]
Merged it. I changed the license to MIT and I removed the filename from the template because a) that looks weird when being used with `help()` and b) most stdlib modules don't have it in there either

**Pull request merged**
